apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: insurance
data:
  AWS_REGION: eu-west-2
  DYNAMODB_TABLE: intl-capstone-team2-claims-dev
  S3_BUCKET: intl-euro-capstone-team2-dev
  JWT_SECRET_NAME: jwt_secret
